### POST request to create a source connector
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "mysql_source_user_profiles",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "connection.url": "jdbc:mysql://host.docker.internal:3306/users?user=root&password=jason",
    "table.whitelist": "users.user_profiles",
    "mode": "timestamp+incrementing",
    "timestamp.column.name": "last_updated",
    "incrementing.column.name": "id",
    "topic.prefix": "users_"
  }
}

###