FROM confluentinc/cp-kafka-connect:8.1.0

COPY ./kafka-setup/kafka-connect-10.9.1/plugins/confluentinc-kafka-connect-jdbc-10.9.1 /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc

ENV CONNECT_PLUGIN_PATH=/usr/share/confluent-hub-components