FROM confluentinc/cp-kafka-connect:8.1.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.9.1

ARG JAR_PATH=./kafka-setup/kafka-connect-10.9.1/plugins/confluentinc-kafka-connect-jdbc-10.9.1/lib
COPY ${JAR_PATH}/mysql-connector-j-9.5.0.jar /usr/share/confluent-hub-components
COPY ${JAR_PATH}/postgresql-42.7.8.jar /usr/share/confluent-hub-components 

ENV CONNECT_PLUGIN_PATH=/usr/share/confluent-hub-components